@controller=http://localhost:8000/api
#@controller=https://perpusstimikapi.stimiksepnop.ac.id/api
@token =Bearer 8|1qcgV4sZ5DIQ1Pi7yVJeFLN6sPkOQ8Cih0LkeC2O
@tokenSimak =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijg3OSIsIlVzZXJuYW1lIjoiMjAxNTExMDk5IiwiRW1haWwiOiJtYWhhc2lzd2FAbWFpbC5jb20iLCJOYW1hVXNlciI6IllPU0VQSCBLVU5HS1VORyIsIlJvbGVVc2VyIjpbeyJOYW1hIjoiTWFoYXNpc3dhIn1dLCJ0aW1lIjoxNjM2NzkyMjM4fQ.RaGHiluQg9p6Zyqy5Nr-DhPUKITHxrMf0HCFH5I0TSU
POST {{controller}}/register  HTTP/1.1
Content-Type: application/json
 
{
    "username": "201511099",
    "email": "ocph23@gmail.com",
    "password": "Sony@77",
    "confirm_password": "Sony@77",
    "name": "Yoseph Kungkung",
    "nomor_induk":"201511099",
    "jenis_kelamin":"L",
    "kewarganegaraan":"WNI", 
    "tempat_lahir":"Palopo",
    "tanggal_lahir":"1979-02-23",
    "agama":"Protestan",
    "jenis":"mahasiswa"
}

###



POST https://restsimak.stimiksepnop.ac.id/api/users/login  HTTP/1.1
Content-Type: application/json

{
    "Username": "201511099",
    "Password": "stimik1011"
}

###




POST {{controller}}/login  HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "Admin123"
}

###


get https://restsimak.stimiksepnop.ac.id/api/Users/GetBiodata  HTTP/1.1
Content-Type: application/json
Authorization: {{tokenSimak}}

####
POST {{controller}}/login  HTTP/1.1
Content-Type: application/json

{
    "username": "kristt26",
    "password": "stimik1011"
}

###




####
POST {{controller}}/login  HTTP/1.1
Content-Type: application/json
Authorization: 

{
    "username": "201511099",
    "password": "Sony@77"
}

###



####
Get {{controller}}/profile  HTTP/1.1
Content-Type: application/json
Authorization: {{token}}


###