//@controller=http://192.168.1.9/perpusstimik/webapp/public/api/penelitian
@controller=http://localhost:8000/api/penelitian
@token = Bearer 77|nqtcJv4hTrITqPTI6yTZdgVsBof3v9ocVftBu1gT



get {{controller}}  HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###



get {{controller}}/1 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###


POST {{controller}}  HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "kode": "123213123",
    "penulis": "Yoseph Kungkung",
    "npm": "Test Penerbit",
    "judul": "apakek",
    "jurusan": "jurusan",
    "topik": "tentang A",
    "jenis": "skripsi",
    "pembimbing":"dosen A",
    "deskripsi":"asdasd",
    "tahun":"2020",
    "kota":"Jayapura"
}

###

get {{controller}}/1/tambahpenelitian/1  HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###


DELETE {{controller}}/17 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}


###