//@controller=http://192.168.1.9/perpusstimik/webapp/public/api/pesanan
@controller=http://localhost:8000/api/pemesanan
@token = Bearer 72|ywd0sne4iixbe1WYv9Fm0W3tEW95xVHi4aQwaEcO


get {{controller}}  HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###  


get {{controller}}/2 HTTP/1.1
Content-Type: application/json
Authorization: {{token}} 

###

POST {{controller}}  HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "kode": "H1252525",
    "anggotaid":1,
    "items":[{"KaryaItemId":1}],
    "tanggal": "2021-09-21"
}

###

get {{controller}}/1/tambahbuku/2  HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###
